{
 "title": "Linux Servers",
 "tags": [ "zabbix" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "netif", "label": "Network interface", "query": "*.$host.Network interfaces.*" }
  ]
 },
 "panels": [
  {
   "title": "Insight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "NUMBER OF CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of CPU" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TOTAL MEMORY",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Total memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU idle time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory in %" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free space on /",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processes" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of processes" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logged in users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Security" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Number of logged in users" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Problems",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "" },
     "mode": 4,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 0,
      "count": true,
      "minSeverity": 1
     }
    }
   ]
  },
  {
   "title": "CPU idle time in %",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory in %",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory in %" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free disk space on / in %",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "iowait time",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "format": "none",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU iowait time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Host Specific Alerts List",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": {
    "zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  { "title": "CPU Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/^CPU*/" },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System load on all cores (1,5,15 min avg.)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Processor load \\([0-9]{1,2} min average all core\\)/"
     },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Memory Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Swap space usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Free swap space" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Filesystem Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Free disk spaces on all partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/Free disk space on \\/\\w*$/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used disk spaces on all partitions in %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "/Used disk space on /\\w* \\(percentage\\)$/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Network Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Network traffic on $netif",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "repeat": "netif",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$netif/" },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}