{
 "title": "Zabbix Server Dashboard",
 "tags": [ "zabbix" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "datasource",
    "label": "Zabbix Data Source",
    "query": "alexanderzobnin-zabbix-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Host name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Host name" },
     "mode": 2
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Zabbix queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Zabbix server" },
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "Zabbix server" },
     "item": { "filter": "Zabbix queue" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "application": { "filter": "CPU" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "CPU idle time" } }
   ]
  },
  {
   "title": "Zabbix processes",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
   "targets": [
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/Zabbix busy/" } }
   ]
  },
  {
   "title": "Zabbix busy processes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/Zabbix busy/" } }
   ]
  },
  {
   "title": "Zabbix Queue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "Zabbix queue" } },
    { "application": { "filter": "Zabbix server" }, "group": { "filter": "Zabbix servers" }, "host": { "filter": "Zabbix server" }, "item": { "filter": "/Values processed/" } }
   ]
  }
 ]
}